// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swgswxqxebwaodsyxnib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3Z3N3eHF4ZWJ3YW9kc3l4bmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTYyOTQsImV4cCI6MjA1NzY5MjI5NH0.XtIGHhf-0xxtvT90ktqJkZN07gScCLhJSgcnX9nzdr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);